if has('python3')
  silent! python3 1
endif

filetype plugin indent on
syntax on

let mapleader = ','

set autoindent
set background=dark
set backspace=indent,eol,start
set encoding=utf-8
set expandtab
set gdefault
set guioptions-=L
set guioptions-=T
set guioptions-=m
set guioptions-=r
set hlsearch
set incsearch
set nocompatible
set number
set relativenumber
set shiftwidth=0
set smartindent
set smarttab
set tabstop=2
set timeoutlen=2000
set wildmenu

inoremap <Down> <nop>
inoremap <Left> <nop>
inoremap <Right> <nop>
inoremap <Up> <nop>
nnoremap <C-C> <C-W><C-C>
nnoremap <C-H> <C-W><C-H>
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <Down> <nop>
nnoremap <Left> <nop>
nnoremap <Right> <nop>
nnoremap <Up> <nop>
nnoremap <silent> - :bdelete<CR>
nnoremap <silent> <BS> :nohlsearch<CR>
nnoremap <silent> <CR> :w<CR>
nnoremap <silent> <S-Tab> :bp<CR>
nnoremap <silent> <Tab> :bn<CR>
nnoremap <silent> H gT
nnoremap <silent> L gt
nnoremap <silent> Q :q<CR>
nnoremap <silent> _ :bdelete!<CR>

call plug#begin()
Plug 'HerringtonDarkholme/yats.vim'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'ap/vim-css-color'
Plug 'flazz/vim-colorschemes'
Plug 'jiangmiao/auto-pairs'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'maxmellon/vim-jsx-pretty'
Plug 'mbbill/undotree'
Plug 'mhinz/vim-startify'
Plug 'octol/vim-cpp-enhanced-highlight'
Plug 'pechorin/any-jump.vim'
Plug 'qpkorr/vim-bufkill'
Plug 'rhysd/vim-clang-format'
Plug 'rhysd/vim-grammarous'
Plug 'ron-rs/ron.vim'
Plug 'rust-lang/rust.vim'
Plug 'ryanoasis/vim-devicons'
Plug 'scrooloose/nerdtree'
Plug 'tikhomirov/vim-glsl'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
if has('nvim')
  Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() } }
  Plug 'neovim/nvim-lspconfig'
  Plug 'nvim-lua/completion-nvim'
endif
call plug#end()

colorscheme gruvbox

if has('nvim')
  lua require('lsp')
endif

augroup vimrc
  autocmd!

  autocmd BufReadPost *
        \ if line("'\"") >= 1 && line("'\"") <= line("$") |
        \   exe "normal! g`\"" |
        \ endif

  if has('win32')
    autocmd GUIEnter * simalt ~x
  endif
augroup END
